[2025-07-02T11:36:50.865+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-02T11:36:50.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_group_ex_dag.end_t manual__2025-07-02T11:35:32.677577+00:00 [queued]>
[2025-07-02T11:36:50.933+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_group_ex_dag.end_t manual__2025-07-02T11:35:32.677577+00:00 [queued]>
[2025-07-02T11:36:50.934+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-07-02T11:36:51.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): end_t> on 2025-07-02 11:35:32.677577+00:00
[2025-07-02T11:36:51.012+0000] {standard_task_runner.py:63} INFO - Started process 865 to run task
[2025-07-02T11:36:51.020+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'task_group_ex_dag', 'end_t', 'manual__2025-07-02T11:35:32.677577+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/task_group_sample.py', '--cfg-path', '/tmp/tmpn5vcmmmn']
[2025-07-02T11:36:51.025+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask end_t
[2025-07-02T11:36:51.060+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-02T11:36:51.146+0000] {task_command.py:426} INFO - Running <TaskInstance: task_group_ex_dag.end_t manual__2025-07-02T11:35:32.677577+00:00 [running]> on host 76fc2b11611c
[2025-07-02T11:36:51.319+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='task_group_ex_dag' AIRFLOW_CTX_TASK_ID='end_t' AIRFLOW_CTX_EXECUTION_DATE='2025-07-02T11:35:32.677577+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-02T11:35:32.677577+00:00'
[2025-07-02T11:36:51.321+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-02T11:36:51.339+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-02T11:36:51.340+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: <lambda>() missing 1 required positional argument: 'x'
[2025-07-02T11:36:51.354+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=task_group_ex_dag, task_id=end_t, run_id=manual__2025-07-02T11:35:32.677577+00:00, execution_date=20250702T113532, start_date=20250702T113650, end_date=20250702T113651
[2025-07-02T11:36:51.373+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task end_t (<lambda>() missing 1 required positional argument: 'x'; 865)
[2025-07-02T11:36:51.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-02T11:36:51.420+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-02T11:36:51.424+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
