[2025-07-03T05:00:57.656+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-03T05:00:57.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.create_table_t manual__2025-07-03T04:59:53.269625+00:00 [queued]>
[2025-07-03T05:00:57.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.create_table_t manual__2025-07-03T04:59:53.269625+00:00 [queued]>
[2025-07-03T05:00:57.706+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-07-03T05:00:57.732+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): create_table_t> on 2025-07-03 04:59:53.269625+00:00
[2025-07-03T05:00:57.738+0000] {standard_task_runner.py:63} INFO - Started process 1415 to run task
[2025-07-03T05:00:57.743+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'create_table_t', 'manual__2025-07-03T04:59:53.269625+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmp6n4s6l3s']
[2025-07-03T05:00:57.748+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask create_table_t
[2025-07-03T05:00:57.773+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-03T05:00:57.840+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.create_table_t manual__2025-07-03T04:59:53.269625+00:00 [running]> on host 2863529924cf
[2025-07-03T05:00:58.001+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='create_table_t' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T04:59:53.269625+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T04:59:53.269625+00:00'
[2025-07-03T05:00:58.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-03T05:00:58.016+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS products_table (
                id INT NOT NULL AUTO_INCREMENT,
                product_id INT NOT NULL,
                product_name VARCHAR(200) NOT NULL,
                price DECIMAL(10, 2) NOT NULL,
                category VARCHAR(50) NOT NULL,
                description TEXT NOT NULL,
                image_link VARCHAR(200) NOT NULL,
                rating DECIMAL(10, 2) NOT NULL,
                rating_count INT NOT NULL,
                date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (product_id, date)
            );
        
[2025-07-03T05:00:58.030+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-07-03T05:00:58.041+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-07-03T05:00:58.066+0000] {sql.py:487} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS products_table (
                id INT NOT NULL AUTO_INCREMENT,
                product_id INT NOT NULL,
                product_name VARCHAR(200) NOT NULL,
                price DECIMAL(10, 2) NOT NULL,
                category VARCHAR(50) NOT NULL,
                description TEXT NOT NULL,
                image_link VARCHAR(200) NOT NULL,
                rating DECIMAL(10, 2) NOT NULL,
                rating_count INT NOT NULL,
                date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (product_id, date)
            );
        , parameters: None
[2025-07-03T05:00:58.075+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-03T05:00:58.076+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key')
[2025-07-03T05:00:58.089+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=products_prices_dag, task_id=create_table_t, run_id=manual__2025-07-03T04:59:53.269625+00:00, execution_date=20250703T045953, start_date=20250703T050057, end_date=20250703T050058
[2025-07-03T05:00:58.138+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 116 for task create_table_t ((1075, 'Incorrect table definition; there can be only one auto column and it must be defined as a key'); 1415)
[2025-07-03T05:00:58.157+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-03T05:00:58.180+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-03T05:00:58.186+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
