[2025-07-04T03:24:32.935+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T03:24:32.967+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:24:32.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:24:32.979+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-04T03:24:33.011+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transfrom_products> on 2025-07-03 00:00:00+00:00
[2025-07-04T03:24:33.016+0000] {standard_task_runner.py:63} INFO - Started process 429 to run task
[2025-07-04T03:24:33.020+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'transfrom_products', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmpfd400nvf']
[2025-07-04T03:24:33.023+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask transfrom_products
[2025-07-04T03:24:33.042+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T03:24:33.101+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T03:24:33.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='transfrom_products' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T03:24:33.411+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T03:24:33.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T03:24:33.443+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/fakestoreapi/get_products.py", line 39, in clean_products
    df = pd.read_csv(f'{path}raw_output.csv', header=True, dtype=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self.options, self.engine = self._clean_options(options, engine)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1615, in _clean_options
    validate_header_arg(options["header"])
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 212, in validate_header_arg
    raise TypeError(
TypeError: Passing a bool to header is invalid. Use header=None for no header or header=int or list-like of ints to specify the row(s) making up the column names
[2025-07-04T03:24:33.475+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=products_prices_dag, task_id=transfrom_products, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T032432, end_date=20250704T032433
[2025-07-04T03:24:33.499+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 154 for task transfrom_products (Passing a bool to header is invalid. Use header=None for no header or header=int or list-like of ints to specify the row(s) making up the column names; 429)
[2025-07-04T03:24:33.515+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T03:24:33.534+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T03:24:33.562+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
