[2025-07-04T03:26:38.442+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T03:26:38.484+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:26:38.496+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:26:38.497+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2025-07-04T03:26:38.531+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transfrom_products> on 2025-07-03 00:00:00+00:00
[2025-07-04T03:26:38.537+0000] {standard_task_runner.py:63} INFO - Started process 512 to run task
[2025-07-04T03:26:38.543+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'transfrom_products', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmprm74oy6e']
[2025-07-04T03:26:38.547+0000] {standard_task_runner.py:91} INFO - Job 157: Subtask transfrom_products
[2025-07-04T03:26:38.570+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T03:26:38.639+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T03:26:39.001+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='transfrom_products' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T03:26:39.004+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T03:26:39.087+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T03:26:39.088+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/fakestoreapi/get_products.py", line 41, in clean_products
    df['rating_count'] = df['rating'].apply(lambda x: x['count'])
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/series.py", line 4764, in apply
    ).apply()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/apply.py", line 1209, in apply
    return self.apply_standard()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/apply.py", line 1289, in apply_standard
    mapped = obj._map_values(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/scripts/fakestoreapi/get_products.py", line 41, in <lambda>
    df['rating_count'] = df['rating'].apply(lambda x: x['count'])
TypeError: string indices must be integers
[2025-07-04T03:26:39.128+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=products_prices_dag, task_id=transfrom_products, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T032638, end_date=20250704T032639
[2025-07-04T03:26:39.151+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 157 for task transfrom_products (string indices must be integers; 512)
[2025-07-04T03:26:39.199+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T03:26:39.232+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T03:26:39.240+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
