[2025-07-04T03:25:17.850+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T03:25:17.889+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:25:17.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T03:25:17.905+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-04T03:25:17.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transfrom_products> on 2025-07-03 00:00:00+00:00
[2025-07-04T03:25:17.948+0000] {standard_task_runner.py:63} INFO - Started process 463 to run task
[2025-07-04T03:25:17.955+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'transfrom_products', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmpw3g1ds4n']
[2025-07-04T03:25:17.959+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask transfrom_products
[2025-07-04T03:25:17.988+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T03:25:18.071+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.transfrom_products scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T03:25:18.401+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='transfrom_products' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T03:25:18.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T03:25:18.447+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T03:25:18.449+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/fakestoreapi/get_products.py", line 39, in clean_products
    df = pd.read_csv(f'{path}raw_output.csv', dtype=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 87, in __init__
    kwds["dtype"] = ensure_dtype_objs(kwds.get("dtype", None))
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 409, in ensure_dtype_objs
    return pandas_dtype(dtype)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/dtypes/common.py", line 1636, in pandas_dtype
    npdtype = np.dtype(dtype)
TypeError: Cannot interpret 'True' as a data type
[2025-07-04T03:25:18.485+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=products_prices_dag, task_id=transfrom_products, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T032517, end_date=20250704T032518
[2025-07-04T03:25:18.529+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 155 for task transfrom_products (Cannot interpret 'True' as a data type; 463)
[2025-07-04T03:25:18.570+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T03:25:18.595+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T03:25:18.602+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
