[2025-06-30T06:14:20.548+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T06:14:20.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_dag.check_price_diff manual__2025-06-30T06:14:15.978121+00:00 [queued]>
[2025-06-30T06:14:20.798+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_dag.check_price_diff manual__2025-06-30T06:14:15.978121+00:00 [queued]>
[2025-06-30T06:14:20.799+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-30T06:14:20.859+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_price_diff> on 2025-06-30 06:14:15.978121+00:00
[2025-06-30T06:14:20.871+0000] {standard_task_runner.py:63} INFO - Started process 1298 to run task
[2025-06-30T06:14:20.878+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_dag', 'check_price_diff', 'manual__2025-06-30T06:14:15.978121+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/mysql.py', '--cfg-path', '/tmp/tmp5zmie9ja']
[2025-06-30T06:14:20.886+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask check_price_diff
[2025-06-30T06:14:20.923+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-30T06:14:21.014+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_dag.check_price_diff manual__2025-06-30T06:14:15.978121+00:00 [running]> on host 76cdd04f4df6
[2025-06-30T06:14:21.164+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Karthik' AIRFLOW_CTX_DAG_ID='mysql_dag' AIRFLOW_CTX_TASK_ID='check_price_diff' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T06:14:15.978121+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T06:14:15.978121+00:00'
[2025-06-30T06:14:21.166+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T06:14:21.285+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/insert_data.py:81 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-30T06:14:21.287+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T06:14:21.288+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/insert_data.py", line 81, in check_price_diff
    df = pd.read_sql_query(query, conn)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 486, in read_sql_query
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2326, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2260, in execute
    cur = self.con.cursor()
  File "/home/airflow/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 762, in cursor
    self.handle_unread_result(prepared)
  File "/home/airflow/.local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 1026, in handle_unread_result
    raise InternalError("Unread result found")
mysql.connector.errors.InternalError: Unread result found
[2025-06-30T06:14:21.319+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_dag, task_id=check_price_diff, run_id=manual__2025-06-30T06:14:15.978121+00:00, execution_date=20250630T061415, start_date=20250630T061420, end_date=20250630T061421
[2025-06-30T06:14:21.368+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 82 for task check_price_diff (Unread result found; 1298)
[2025-06-30T06:14:21.413+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T06:14:21.444+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T06:14:21.451+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
