[2025-07-04T05:35:33.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T05:35:33.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.mail_group.send_alert scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:35:33.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.mail_group.send_alert scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:35:33.522+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-07-04T05:35:33.550+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): mail_group.send_alert> on 2025-07-03 00:00:00+00:00
[2025-07-04T05:35:33.559+0000] {standard_task_runner.py:63} INFO - Started process 4802 to run task
[2025-07-04T05:35:33.566+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'mail_group.send_alert', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmpreouhpro']
[2025-07-04T05:35:33.574+0000] {standard_task_runner.py:91} INFO - Job 219: Subtask mail_group.send_alert
[2025-07-04T05:35:33.607+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T05:35:33.692+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.mail_group.send_alert scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T05:35:33.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='mail_group.send_alert' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T05:35:33.866+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T05:35:33.918+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-04T05:35:33.919+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-04T05:35:33.920+0000] {email.py:271} INFO - Email alerting: attempt 1
[2025-07-04T05:35:33.923+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T05:35:33.925+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-04T05:35:33.940+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=products_prices_dag, task_id=mail_group.send_alert, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T053533, end_date=20250704T053533
[2025-07-04T05:35:33.990+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 219 for task mail_group.send_alert ([Errno 111] Connection refused; 4802)
[2025-07-04T05:35:34.021+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T05:35:34.059+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T05:35:34.070+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
